import type { ModuleDefinition, ModuleId } from '@boq/shared';
import type { CalcContext, ModuleOutput } from './helpers';
import type { MeasurementEntry } from '@boq/shared';
import * as M from './modules';

const mixOptions = [
  { value: '1:4:8', label: '1:4:8 (Lean)' },
  { value: '1:3:6', label: '1:3:6' },
  { value: '1:2:4', label: '1:2:4 (Standard)' },
  { value: '1:1.5:3', label: '1:1.5:3 (Rich)' },
  { value: '1:1:2', label: '1:1:2 (Very Rich)' },
];

export const MODULE_DEFINITIONS: ModuleDefinition[] = [
  {
    id: 'excavation',
    name: 'Excavation',
    description: 'Earthwork excavation volume from L × W × D',
    category: 'Earthwork',
    icon: 'shovel',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, step: 0.01, required: true, tooltip: 'Plan length of excavation' },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'depth', label: 'Depth', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', min: 1, step: 1, defaultValue: 1 },
    ],
  },
  {
    id: 'pcc',
    name: 'PCC',
    description: 'Plain cement concrete lean mix',
    category: 'Concrete',
    icon: 'layers',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'thickness', label: 'Thickness', unit: 'm', type: 'number', min: 0, step: 0.005, defaultValue: 0.075, tooltip: 'Typical PCC under footing: 75mm' },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', min: 1, defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:4:8' },
    ],
  },
  {
    id: 'rcc',
    name: 'RCC',
    description: 'Reinforced cement concrete with steel & formwork',
    category: 'Concrete',
    icon: 'box',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'depth', label: 'Depth / Thickness', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', min: 1, defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:2:4' },
      {
        key: 'element',
        label: 'Element',
        type: 'select',
        defaultValue: 'general',
        options: [
          { value: 'general', label: 'General' },
          { value: 'footing', label: 'Footing' },
          { value: 'column', label: 'Column' },
          { value: 'beam', label: 'Beam' },
          { value: 'slab', label: 'Slab' },
        ],
      },
    ],
  },
  {
    id: 'foundation',
    name: 'Foundation',
    description: 'Complete footing: excavation, PCC, RCC, backfill',
    category: 'Substructure',
    icon: 'foundation',
    fields: [
      { key: 'length', label: 'Footing Length', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'width', label: 'Footing Width', unit: 'm', type: 'number', min: 0, step: 0.01, required: true },
      { key: 'depth', label: 'Excavation Depth', unit: 'm', type: 'number', min: 0, step: 0.01, required: true, tooltip: 'Depth from ground to PCC bottom' },
      { key: 'pccThickness', label: 'PCC Thickness', unit: 'm', type: 'number', defaultValue: 0.075, step: 0.005 },
      { key: 'rccThickness', label: 'RCC Thickness', unit: 'm', type: 'number', defaultValue: 0.23, step: 0.01 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', min: 1, defaultValue: 1 },
      { key: 'mix', label: 'RCC Mix', type: 'select', options: mixOptions, defaultValue: '1:2:4' },
    ],
  },
  {
    id: 'footings',
    name: 'Footings',
    description: 'Isolated / combined footing quantities',
    category: 'Substructure',
    icon: 'foundation',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'depth', label: 'Excavation Depth', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'pccThickness', label: 'PCC Thickness', unit: 'm', type: 'number', defaultValue: 0.075 },
      { key: 'rccThickness', label: 'RCC Thickness', unit: 'm', type: 'number', defaultValue: 0.3 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'mix', label: 'RCC Mix', type: 'select', options: mixOptions, defaultValue: '1:2:4' },
    ],
  },
  {
    id: 'columns',
    name: 'Columns',
    description: 'RCC column concrete, steel & formwork',
    category: 'Structure',
    icon: 'columns',
    fields: [
      { key: 'length', label: 'Section Length', unit: 'm', type: 'number', min: 0, required: true, tooltip: 'Cross-section dimension a' },
      { key: 'width', label: 'Section Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Storey Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:1.5:3' },
    ],
  },
  {
    id: 'beams',
    name: 'Beams',
    description: 'RCC beam concrete, steel & formwork',
    category: 'Structure',
    icon: 'beam',
    fields: [
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'depth', label: 'Depth', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:2:4' },
    ],
  },
  {
    id: 'slabs',
    name: 'Slabs',
    description: 'RCC slab with shuttering & reinforcement',
    category: 'Structure',
    icon: 'slab',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'thickness', label: 'Thickness', unit: 'm', type: 'number', defaultValue: 0.125, tooltip: 'Typical residential slab 125–150mm' },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:2:4' },
    ],
  },
  {
    id: 'staircase',
    name: 'Staircase',
    description: 'RCC staircase waist slab & steps',
    category: 'Structure',
    icon: 'stairs',
    fields: [
      { key: 'going', label: 'Going (Tread)', unit: 'm', type: 'number', defaultValue: 0.275 },
      { key: 'rise', label: 'Rise', unit: 'm', type: 'number', defaultValue: 0.175 },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', defaultValue: 1.2 },
      { key: 'steps', label: 'No. of Steps', unit: 'nos', type: 'number', defaultValue: 12 },
      { key: 'waist', label: 'Waist Thickness', unit: 'm', type: 'number', defaultValue: 0.15 },
      { key: 'quantity', label: 'Flights', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:2:4' },
    ],
  },
  {
    id: 'masonry',
    name: 'Masonry Walls',
    description: 'Brick masonry with mortar & openings deduction',
    category: 'Masonry',
    icon: 'brick',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'thickness', label: 'Thickness', unit: 'm', type: 'number', defaultValue: 0.23, tooltip: '9″ = 0.23m, 4.5″ = 0.115m' },
      { key: 'openings', label: 'Openings Volume', unit: 'm3', type: 'number', defaultValue: 0 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'blockwork',
    name: 'Block Walls',
    description: 'Hollow concrete block masonry',
    category: 'Masonry',
    icon: 'block',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'thickness', label: 'Thickness', unit: 'm', type: 'number', defaultValue: 0.15 },
      { key: 'openings', label: 'Openings Volume', unit: 'm3', type: 'number', defaultValue: 0 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'boundary-wall',
    name: 'Boundary Walls',
    description: 'Boundary wall masonry with optional coping',
    category: 'Masonry',
    icon: 'fence',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'thickness', label: 'Thickness', unit: 'm', type: 'number', defaultValue: 0.23 },
      { key: 'copingWidth', label: 'Coping Width', unit: 'm', type: 'number', defaultValue: 0.3 },
      { key: 'copingThk', label: 'Coping Thickness', unit: 'm', type: 'number', defaultValue: 0.05 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'plaster',
    name: 'Plaster',
    description: 'Cement plaster area & materials',
    category: 'Finishes',
    icon: 'paintbrush',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'thickness', label: 'Thickness (mm)', type: 'number', defaultValue: 12, tooltip: 'Plaster thickness in millimetres (e.g. 12 or 20)' },
      { key: 'sides', label: 'Sides', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'openings', label: 'Openings Area', unit: 'm2', type: 'number', defaultValue: 0 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'paint',
    name: 'Paint',
    description: 'Paint, primer & putty takeoff',
    category: 'Finishes',
    icon: 'droplet',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'coats', label: 'Coats', unit: 'nos', type: 'number', defaultValue: 2 },
      { key: 'openings', label: 'Openings Area', unit: 'm2', type: 'number', defaultValue: 0 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'floor-tiles',
    name: 'Floor Tiles',
    description: 'Floor tile area with adhesive & grout',
    category: 'Finishes',
    icon: 'grid',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'wall-tiles',
    name: 'Wall Tiles',
    description: 'Wall tile cladding takeoff',
    category: 'Finishes',
    icon: 'grid',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'roofing',
    name: 'Roofing',
    description: 'Roof screed & waterproofing',
    category: 'Roofing',
    icon: 'home',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'waterproofing',
    name: 'Waterproofing',
    description: 'Membrane waterproofing area',
    category: 'Waterproofing',
    icon: 'shield',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'doors',
    name: 'Doors',
    description: 'Door shutters by count & size',
    category: 'Openings',
    icon: 'door',
    fields: [
      { key: 'width', label: 'Width', unit: 'm', type: 'number', defaultValue: 0.9 },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', defaultValue: 2.1 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1, required: true },
    ],
  },
  {
    id: 'windows',
    name: 'Windows',
    description: 'Aluminium windows by count & size',
    category: 'Openings',
    icon: 'window',
    fields: [
      { key: 'width', label: 'Width', unit: 'm', type: 'number', defaultValue: 1.2 },
      { key: 'height', label: 'Height', unit: 'm', type: 'number', defaultValue: 1.2 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1, required: true },
    ],
  },
  {
    id: 'ceiling',
    name: 'Ceiling',
    description: 'False / gypsum ceiling area',
    category: 'Finishes',
    icon: 'ceiling',
    fields: [
      { key: 'length', label: 'Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
    ],
  },
  {
    id: 'steel-bbs',
    name: 'Steel Reinforcement (BBS)',
    description: 'Bar bending — weight from Ø, length & count',
    category: 'Steel',
    icon: 'steel',
    fields: [
      { key: 'diameter', label: 'Bar Diameter (mm)', type: 'number', defaultValue: 12, tooltip: 'Bar diameter in millimetres (e.g. 12, 16, 20)' },
      { key: 'length', label: 'Length per Bar', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'bars', label: 'No. of Bars', unit: 'nos', type: 'number', min: 1, defaultValue: 1 },
    ],
  },
  {
    id: 'water-tank',
    name: 'Water Tank',
    description: 'RCC water tank structure & capacity',
    category: 'Water Works',
    icon: 'tank',
    fields: [
      { key: 'length', label: 'Internal Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Internal Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Internal Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'wallThickness', label: 'Wall Thickness', unit: 'm', type: 'number', defaultValue: 0.15 },
      { key: 'baseThickness', label: 'Base Thickness', unit: 'm', type: 'number', defaultValue: 0.15 },
      { key: 'coverThickness', label: 'Cover Thickness', unit: 'm', type: 'number', defaultValue: 0.1 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:1.5:3' },
    ],
  },
  {
    id: 'septic-tank',
    name: 'Septic Tank',
    description: 'RCC septic tank structure',
    category: 'Water Works',
    icon: 'tank',
    fields: [
      { key: 'length', label: 'Internal Length', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'width', label: 'Internal Width', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'height', label: 'Internal Height', unit: 'm', type: 'number', min: 0, required: true },
      { key: 'wallThickness', label: 'Wall Thickness', unit: 'm', type: 'number', defaultValue: 0.23 },
      { key: 'baseThickness', label: 'Base Thickness', unit: 'm', type: 'number', defaultValue: 0.15 },
      { key: 'coverThickness', label: 'Cover Thickness', unit: 'm', type: 'number', defaultValue: 0.1 },
      { key: 'quantity', label: 'Nos', unit: 'nos', type: 'number', defaultValue: 1 },
      { key: 'mix', label: 'Mix', type: 'select', options: mixOptions, defaultValue: '1:2:4' },
    ],
  },
];

type Calculator = (entry: MeasurementEntry, ctx: CalcContext) => ModuleOutput;

const CALCULATORS: Record<ModuleId, Calculator> = {
  excavation: M.calcExcavation,
  pcc: M.calcPCC,
  rcc: M.calcRCC,
  foundation: M.calcFoundation,
  footings: M.calcFootings,
  columns: M.calcColumns,
  beams: M.calcBeams,
  slabs: M.calcSlabs,
  staircase: M.calcStaircase,
  masonry: M.calcMasonry,
  blockwork: M.calcBlockwork,
  'boundary-wall': M.calcBoundaryWall,
  plaster: M.calcPlaster,
  paint: M.calcPaint,
  'floor-tiles': M.calcFloorTiles,
  'wall-tiles': M.calcWallTiles,
  roofing: M.calcRoofing,
  waterproofing: M.calcWaterproofing,
  doors: M.calcDoors,
  windows: M.calcWindows,
  ceiling: M.calcCeiling,
  'steel-bbs': M.calcSteelBBS,
  'water-tank': M.calcWaterTank,
  'septic-tank': M.calcSepticTank,
};

export function getModule(id: ModuleId): ModuleDefinition | undefined {
  return MODULE_DEFINITIONS.find((m) => m.id === id);
}

export function runModule(entry: MeasurementEntry, ctx: CalcContext): ModuleOutput {
  const calc = CALCULATORS[entry.moduleId];
  if (!calc) return { quantities: [], materials: [], labour: [], equipment: [], boq: [] };
  return calc(entry, ctx);
}
